<div class="banner">
<a href="/tool/input"><img src="/img/common/banner_tool_off.jpg" alt="中国向けWEBサイトパフォーマンスツール" /></a>
</div>

<div class="banner">
<a href="http://markezine.jp/article/detail/14312" target="_blank"><img src="/img/common/banner_markezine.jpg" alt="中国Webマーケティング最前線" /></a>
</div>

<div class="banner">
<a href="/partner/"><img src="/img/common/banner_partner_off.jpg" alt="セールスパートナーのお問い合わせ" /></a>
</div>