<div id="footer">
<div id="footer-inner">
<div id="f-navi" class="clearfix">
<ul>
<li><a href="/">ホーム</a></li>
<li><a href="/pr">中国4大ポータル記事掲載保証 PR</a></li>
<li><a href="/rapid">中国語サイト快速サービス</a></li>
<li><a href="/kujapan">訪日中国人観光客集客サイト「日遊酷棒」</a></li>
<li><a href="/tool/input">中国向けWEBサイトパフォーマンスツール</a></li>
<li><a href="/inquiry/input">お問い合わせ</a></li>
<li><a href="/corp">運営</a></li>
</ul>
</div><!--#f-navi-->
<div id="footer-bottom" class="clearfix">

<div id="footer-group">[グループサイト] <a href="http://www.serviced-apartments-tokyo.com/">東京サービスアパートメント</a> | <a href="http://www.kujapan.com/">日遊酷棒</a></div>

<div id="copyright">
<img src="/img/common/copyright.gif" alt="Copyroght (c) HACHIONE Inc. All Right Reserved." width="270" height="30" />
</div><!--#copyright-->
</div><!--#footer-bottom-->
</div><!--#footer-inner-->
</div><!--#footer-->
{include file="include/common/analytics.inc"}