<div id="header" class="clearfix">
    <div id="logo"><h1>{$h1}</h1><a href="/"><img src="/img/common/logo.jpg" alt="China Adviser(チャイナアドバイザー)" /></a></div>
    <div id="c-navi">
        <div id="c-img">
        <img src="/img/common/contact_img01.jpg" alt="中国市場開拓を目指す企業様をサポート" />
        </div>
        <div id="c-bt">
        <a href="/inquiry/input"><img src="/img/common/bt_contact01_off.jpg" alt="お問い合わせはこちら" /></a>
        </div>
    </div>
    {*position*}
    {include file="include/common/position.inc"}
</div><!--#header-->
