<div id="g-navi">
<div id="g-navi-new">
<h3><img src="/img/common/gnavi_top.jpg" alt="サービス一覧" /></h3>
<ul>
<li class="navy"><a href="/pr">中国4大ポータル記事掲載保証PR</a></li>
<li class="navy"><a href="/rapid">中国サイト快速サービス</a></li>
<li class="navy"><a href="/kujapan">日遊酷棒（リーヨウクーバン）</a></li>
<li class="navy"><a href="/bbs">中国BBS口コミPR</a></li>
<li class="navy"><a href="/microblog">中国マイクロブログ（微博）PR</a></li>
<li class="navy"><a href="/blogger">中国人気ブロガーPR</a></li>
<li class="navy"><a href="/baike">百度百科登録</a></li>
<li class="navy"><a href="/zhidao">百度知道登録</a></li>
</ul>
</div>

<div class="banner">
<a href="/tool/input"><img src="/img/common/banner_tool_off.jpg" alt="中国向けWEBサイトパフォーマンスツール" /></a>
</div>

<div class="banner">
<a href="/partner/"><img src="/img/common/banner_partner_off.jpg" alt="セールスパートナーのお問い合わせ" /></a>
</div>

</div><!--#g-navi-->
