<div id="g-navi">
<div id="g-navi01">
<h3><a href="/pr"><img src="/img/common/gnavi01_off.jpg" alt="中国4大ポータル記事掲載保証 PR" /></a></h3>
<ul>
<li><a href="/pr#pr01">中国4大ポータル記事掲載保証PRとは？</a></li>
<li><a href="/pr#pr02">4つの保証</a></li>
<li><a href="/pr#pr03">中国でプロモーションをする際の6つの課題</a></li>
<li><a href="/pr#pr04">サービス概要</a></li>
</ul>
</div>

<div id="g-navi02">
<h3><a href="/rapid"><img src="/img/common/gnavi02_off.jpg" alt="中国語サイト快速サービス" /></a></h3>
<ul>
<li><a href="/rapid#ex01">中国語サイト快速サービスとは？</a></li>
<li><a href="/rapid#ex02">中国向けWEBサイトの課題</a></li>
<li><a href="/rapid#ex05">表示速度例</a></li>
</ul>
</div>

<div id="g-navi03">
<h3><a href="kujapan/"><img src="/img/common/gnavi03_off.jpg" alt="訪日中国人観光客集客サイト「日遊酷棒」" /></a></h3>
<ul>
<li><a href="/kujapan#kj01">日遊酷棒（リーヨウクーバン）とは？</a></li>
<li><a href="/kujapan#kj02">仕組み</a></li>
<li><a href="/kujapan#kj03">大手が続々参加</a></li>
<li><a href="/kujapan#kj04">掲載料金は一切無料</a></li>
<li><a href="/kujapan#kj05">サーバーは中国なので快速アクセス</a></li>
</ul>
</div>


<div class="banner">
<a href="/tool/input"><img src="/img/common/banner_tool_off.jpg" alt="中国向けWEBサイトパフォーマンスツール" /></a>
</div>

</div><!--#g-navi-->
