    <div id="g-navi-new">
    <h3><img src="/img/common/news_top.jpg" alt="お知らせ" /></h3>
    <ul>
    <li class="navy">冬季休暇のお知らせ<br />2011年12月29日（木）-<br />2012年1月4日（水）<br />※2012年1月5日（木）より通常営業を開始いたします。</li>
    <li class="navy"><a href="http://startbiz.jp/atcl/asia/" target="blank">2011/12/19<br />START BIZ JAPANに弊社が取り上げられました。</a></li>
    <li class="navy"><a href="/special/nikkan">2011/10/10<br />日刊工業新聞に弊社矢作の記事が掲載されました。</a></li>
    <li class="navy"><a href="http://markezine.jp/article/detail/14356" target="blank">2011/10/06<br />弊社の中国Webマーケティング記事がMarkezineで掲載されました。</a></li>
    </ul>
    </div>