    <div id="g-navi-new">
    <h3><img src="/img/common/news_top.jpg" alt="お知らせ" /></h3>
    <ul>
    <li class="navy"><a href="/seo">2012/1/12<br />中国検索エンジン最大手 百度（Baidu）SEOサービス開始。</a></li>
    <li class="navy"><a href="/weibo">2012/1/11<br />中国版TwitterのWeibo(微博)運用代行サービス開始。</a></li>
    <li class="navy"><a href="http://startbiz.jp/atcl/asia/" target="blank">2011/12/19<br />START BIZ JAPANに弊社が取り上げられました。</a></li>
    <li class="navy"><a href="/special/nikkan">2011/10/10<br />日刊工業新聞に弊社矢作の記事が掲載されました。</a></li>
    <li class="navy"><a href="http://markezine.jp/article/detail/14356" target="blank">2011/10/06<br />弊社の中国Webマーケティング記事がMarkezineで掲載されました。</a></li>
    </ul>
    </div>